### ISSUE TITLE
partial image showing

### ISSUE THREAD

**Issue by christianPBD** [stevenwanderski/bxslider-3#112]
Im a self proclaimed novice at coding. I know enough to get into trouble but not enough to get out.

having some issues on chrome and ipad. only the top 20-or-so pixels of the images are showing up of the slideshow.
they are loading, auto starting, and fading properly but it looks as if most of it is hidden somehow. 

any ideas?
overflow is hidden
margins and padding are set to 0.

thanks.
-chris

**Comment by christianPBD** [comment]
well, it looks as if it is happening on all browsers. but if you click the link a second time, it loads fine.
so it seems initial display of the slider is wonky. any help. heeellllooooooooo.

thanks.
-chris

**Comment by christianPBD** [comment]
OK... so it seems to only be an issue with mode: 'fade'. horizontal works fine across all the browsers. I'd REALLY like these to fade so if anyone has any ideas. looks like a mode issue.

**Comment by tomsinger** [comment]
@christianPBD had the same issue, looking at the code it's because it calculates the height of all the list items when the slideshow initialises. If the browser hasn't completed rendering if for example the images in the slideshow haven't downloaded then it won't be able to calculate the height for bx-window correctly. Do you have a height on the li elements? If not try adding one to see if this fixes the issue.

For a code fix the code needs to wait until all images have been downloaded which I'll look at in a bit but specifying heights should work in the mean time.

**Comment by tomsinger** [comment]
In fact on http://bxslider.com/examples it does state "To ensure webkit browsers display the slideshow correctly - ALWAYS DECLARE A HEIGHT AND WIDTH ON YOUR IMAGES!!" since images should have a width and height anyway I think this is an implementation rather than a code issue.

**Comment by christianPBD** [comment]
tom. thank you thank you thank you. for both explaining my issue and suggesting a solution. at first I said: no, I totally have all the heights and widths for all my images. and you know, I didn't. that was my issue. this appears to have fixed the problem. seems like such a remedial mistake, Im actually sort of embarrassed. but perhaps someone else may learn from my silly mistake.

again, I really appreciate it!!!

**Comment by tomsinger** [comment]
No problem, glad I could help :)

**Comment by ghost** [comment]
I just had the same problem but with textual content instead of images. The solution was to assign a height to the list elements.

Cheers tom!
